### ISSUE TITLE
JOSS Review: Dependencies

### ISSUE THREAD

**Issue by meghnathomas** [tylertrimble/viswaternet#103]
Based on issue #101 and #99:

> There are a few deprecation warnings generated when running the tests; in particular the matplotlib ones may be cause for concern -- you don't want upstream changes to matplotlib to break your code. It would be preferable to update your use of matplotlib APIs to the latest syntax, but you could alternatively pin the maximum allowed matplotlib version in your requirements.txt.

- [x] Check deprecation warnings for matplotlib and either specify lower + upper matplotlib version or update the code to represent new cmap functions (and then change the minimum required version)
- [x] Same for NetworkX
- [ ] Same for WNTR

**Comment by tylertrimble** [comment]
The warning being thrown by matplotlib about offsets due to networkx appears to be related to [this](https://github.com/networkx/networkx/pull/5173/commits). This was fixed in networkx 2.7, so we can make this the minimum version and that error won't appear. 

Additionally, I think we should change python support for 3.8+ instead of 3.7+, since networkx claims to only support 3.8+ on networkx 2.7 and higher.

**Comment by tylertrimble** [comment]
The matplotlib function matplotlib.cm.get_cmap() was replaced by matplotlib.colormaps[cmap] in matplotlib 3.5.0.

After testing the replacement in our code, everything appears to be working just as normal on all our example files and tests. So I think we can set the lower bound on matplotlib at 3.5.0!

**Comment by tylertrimble** [comment]
It appears that the test is failing here with matplotlib 3.7.2, I am on 3.5.2 on my PC at the new colormap function works fine... will do some more testing

**Comment by tylertrimble** [comment]
Fixed! It turns out that there were nested colormap calls that worked fine with the old function and not the new function. Makes total sense that matplotlib.colormaps[matplotlib.colormaps[cmap]] doesn't work, and I'm surprised get_cmap allowed this.

**Comment by tylertrimble** [comment]
Setting WNTR 0.2.2 as the minimum WNTR result is most likely sufficient, as this was the last time network morphology was updated (at least it appears to be) and that is the main functionality that we use from WNTR. The other functionality, which is mostly just getting network simulator results, is likely not to have changed much, if at all, from early versions (which no one should be using anyway.)
