### ISSUE TITLE
JOSS Review: Links in legend

### ISSUE THREAD

**Issue by meghnathomas** [tylertrimble/viswaternet#104]
Based on issue #101 and #93:

> In Example 2, when plotting the pumps as dotted lines, it would be nice if the legend also updated to show pumps in dotted lines. 

- [x] Update legend inputs from patches to line objects
- [x] Remove pump from legend if there are no pumps in the system
- [x] Remove pipe from legend if calling on `plot_continuous_links`, `plot_discrete_links`, or `plot_unique_data` for links

**Comment by tylertrimble** [comment]
All legend elements relating to links will now show up as line elements. One limitation for now is that if arrows are turned on for links/pumps then it is not reflected in the legend. It seems that adding that to the legend automatically is slightly more involved.

Additionally, the pump line will not be drawn if there are no pumps, and the link line will not be drawn if plotting link parameters.
Examples:
![image](https://user-images.githubusercontent.com/102005076/222941368-c66677a1-7819-4a49-a2c1-a824769518fd.png)
--------------------------------------------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/102005076/222941383-9a7c7dab-801b-48c7-bb4a-5615ae878bf9.png)
--------------------------------------------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/102005076/222941392-2ecad9a6-d939-4602-afba-0659c6f4f76b.png)
