### ISSUE TITLE
JOSS Review: Default axis

### ISSUE THREAD

**Issue by meghnathomas** [tylertrimble/viswaternet#106]
Based on issue #101: 

> Could be nice to support an ax=None default argument that creates a matplotlib fig/ax on behalf of the user. This would follow the precedent of libraries like pandas/xarray.

- [ ] Test the implementation of a default axis.

**Comment by tylertrimble** [comment]
A default figure and axis is now created when no axis is specified. The changes can be seen in the updated example files, which no longer have a figure and axis creation step.

Additionally, the user can specify the figsize (duple) and if a frame is drawn around the axis when creating the model with VisWNModel
