### ISSUE TITLE
JOSS Review: Warnings

### ISSUE THREAD

**Issue by meghnathomas** [tylertrimble/viswaternet#107]
From issues #101:

> When running through the example in the GitHub README.md, a warning is generated -- would be good to either suppress it if it's irrelevant to your package, or more fully explain it so the user knows what should be done: `/Users/thur961/viswaternet/venv/lib/python3.10/site-packages/wntr/epanet/io.py:2082: UserWarning: Not all curves were used in "/Users/thur961/viswaternet/CTown.inp"; added with type None, units conversion left to user warnings.warn('Not all curves were used in "{}"; added with type None, units conversion left to user'.format(self.wn.name))`

Add list of likely warning messages to docs.

**Comment by tylertrimble** [comment]
Since this is an issue that only occurs on some input files (Only CTown so far) should I try to suppress it as well?

**Comment by meghnathomas** [comment]
@tylertrimble no that's fine but thanks for offering! i'll add a line in the docs about this warning and i'll modify the CTown inp file so it doesn't show up in the future. better to leave warnings in for now
