### ISSUE TITLE
JOSS REVIEW: WNTR get_graph deprecation warning

### ISSUE THREAD

**Issue by tylertrimble** [tylertrimble/viswaternet#116]
@meghnathomas I'm not sure what to do here, as WNTR 0.5.0 is the latest version, and the get_graph function was deprecated in it but still works. Should we switch over to only allowing WNTR 0.5.0 or wait until deprecation becomes removal?

**Comment by meghnathomas** [comment]
@tylertrimble when/where does this deprecation warning pop up for you? and this is a WNTR warning not a networkx warning?

**Comment by meghnathomas** [comment]
we can discuss tomorrow but leaning towards capping WNTR <0.5.0. WNTR version 0.5.0 doesn't have significant solver updates, etc, that would warrant necessary upgrades to those versions  IMO but i'm asking around to see what version others are using. we can add more detailed steps regarding creating virtual environments to run viswaternet scripts maybe?

**Comment by tylertrimble** [comment]
Changed requirements to wntr>=0.5.0 for python 10 support and changed wn.get_graph() to wn.to_graph() to resolve deprecation warning.
