### ISSUE TITLE
not urgent: allowing png icons?

### ISSUE THREAD

**Issue by meghnathomas** [tylertrimble/viswaternet#129]
wondering if we should consider allowing users to import png icons as node markers?
i have a script that does this but it's not straightforward to add these icons to a legend

**Comment by tylertrimble** [comment]
I just added functionality to import custom svg markers. It wouldn't be hard to convert pngs to svgs in code as well.

However, adding svg markers adds two new package dependencies (for now I'm generating the marker data outside of the actual package,) and adding png2svg functionality would add another. Would this be fine?
