### ISSUE TITLE
New marker for valves

### ISSUE THREAD

**Issue by gregrhend** [tylertrimble/viswaternet#137]
As discussed, here's a new marker for valves that resembles the EPANET marker. This marker by default is oriented vertically, additional code is needed to align the valve marker with the direction of the link.

# vertices that define marker
verts = [
    (-1,-1),
    (1,-1),
    (0,0),
    (-1,-1),
    (-1,1),
    (1,1),
    (0,0),
    (-1,1)
    ]

# lines that draw marker
lines = [
    Path.MOVETO, #begin the figure in the lower right
    Path.LINETO, #start a 3 point curve with the control point in lower left
    Path.LINETO, #end curve in the upper left
    Path.LINETO, #start a new 3 point curve with the upper right as a control point
    Path.MOVETO, #begin the figure in the lower right
    Path.LINETO, #start a 3 point curve with the control point in lower left
    Path.LINETO, #end curve in the upper left
    Path.LINETO, #start a new 3 point curve with the upper right as a control point
]

marker = Path(verts,lines)

**Comment by tylertrimble** [comment]
Thank you Greg! I added this to the code, and also created a epanet pump icon as well. I'll add the other epanet icons soon but I have to recreate them first in .svg format first.
