### ISSUE TITLE
master list of legend issues 

### ISSUE THREAD

**Issue by meghnathomas** [tylertrimble/viswaternet#141]
- [x] plot_unique_data with excel: the two legends are joined into one. (maybe this should be an option? to consolidate legends?) (see example 9)
- [x] plot_unique_data demand pattern and diameter plots: legend cannot be moved (see examples 7 and 8)
- [x] plot_unique_data: cannot turn base legend off (see issue #140 )
- [x] plot_unique_data with node AND link data: only colorbar appears, legend does not show up (see issue #139 )

**Comment by meghnathomas** [comment]
legend not showing up issue seems to be fixed with previous push

**Comment by tylertrimble** [comment]
All fixed on my end, will push in a moment
