### ISSUE TITLE
pumps don't show up any more

### ISSUE THREAD

**Issue by meghnathomas** [tylertrimble/viswaternet#144]
if i call plot_basic_elements on network CTown, the pumps no longer show up! what's happening here?

![image](https://github.com/tylertrimble/viswaternet/assets/74310847/47a1c8dd-dab9-452b-a3b6-70cec2fc0bf8)

**Comment by meghnathomas** [comment]
note - the pumps show up fine on plot_continuous_nodes etc, they only seem to be a problem with plot_basic_elements [🤔](https://emojipedia.org/thinking-face)

**Comment by tylertrimble** [comment]
An if statement was incorrect. It was meant to check to make sure there are pumps in the model, and if not, prevent the code from attempting to plot them.
