### ISSUE TITLE
Come up with better parameter names

### ISSUE THREAD

**Issue by tylertrimble** [tylertrimble/viswaternet#149]
There are a lot of parameter names that sound similar but do very different things, as well as some inconsistences between functions. I think it would be worth looking over the parameter names are renaming them as we see fit to be more clear, concise, and consistent.

**Comment by meghnathomas** [comment]
come up with all redundant arguments and go through them together

**Comment by tylertrimble** [comment]
Add "interval_link_stle" and "interval_link_arrows" for better consistency

**Comment by meghnathomas** [comment]
oof!

- [ ] for discrete plotting functions, replace legend_loc_1 with legend_loc and legend_loc_2 with discrete_legend_loc
- [ ]  for discrete link plotting add "interval_link_style" and "interval_link_arrows" for better consistency
- [ ] replace file format in animate function to the same as for the static plots
- [ ] replace node_size/node_sizes in plot_unique_data
- [ ] 
- [ ] delete node_size argument
- [ ] delete widths argument
- [ ] delete link_sizes argument
- [ ] interval_node_shape_list --> node_shape (str,list)
- [ ] interval_node_size_list, node_size, node_sizes, min_size, max_size --> node_size (int, list, tuple)
- [ ] line_widths, interval_node_border_width_list --> node_border_width (int,list)
- [ ] edge_colors, interval_node_border_color_list --> node_border_colors (str,list)
- [ ] interval_link_width_list, widths, min_width, max_width,  --> link_width (int, list, tuple)
- [ ] element_size_intervals --> custom_legend_intervals
- [ ] element_size_legend_title -->
- [ ] ... loc
- [ ] ... labels
- [ ] disable_interval_deleting
- [ ] file_format --> save_format
- [ ] 
- [ ] (not urgent!!!!!) get_tanks, get_reservoirs --> include_tanks, include_reservoirs
- [ ] (not urgent!!!!!) add include_pumps
- [ ] (not urgent!!!!) add include_valves
- [ ] nodes, links, tanks, reservoirs, pumps, valves --> add 'draw_' in front!
- [ ] legend --> draw_discrete_legend
- [ ] base_legend --> draw_base_legend
- [ ] font_size, font color --> legend_label_font_size, legend_label_font_color
- [ ] add legend_title_font_color
- [ ] draw_frame --> draw_legend_frame
- [ ] legend_sig_figs --> legend_decimal_places

**Comment by tylertrimble** [comment]
Keeping the following the same for now:
element_size_intervals
element_size_legend_title
disablle_interval_deleting
