### ISSUE TITLE
steps for next release

### ISSUE THREAD

**Issue by meghnathomas** [tylertrimble/viswaternet#153]
- [x] pull dev changes into main
- [x] make new res and tank icons sharper
- [x] all plotting functions should have default black epanet res, tank, valve, pump icons
- [x] revert example 11 back to what it was
- [x] check all units (some italicized some not?)
- [x] add viswaternet paper and option to cite on landing page
- [x] plot unique data: node and link plots with unique data club legends together
- [x] plot unique data: link plots - valves don't show up
- [x] unique.py line 193 - fix typo (node size)
- [x] add new examples mentioned in previous issue
- [x] make sure list of junction names doesn't print (after all debugging is done)
- [x] discrete_links headloss plot doesn't show up unless legend title is specified
- [x] j'lynn -pull from dev
- [x] j'lynn - create continuous links ipynb file
- [x] tyler - add issues with code breaking
- [x] tyler - eventually push dev to main
- [x] links (continuous and discrete): the draw_nodes function results in nodes being drawn even when this is defined as false
- [x] continuous nodes: vmin, vmax don't affect colorbar - tyler
- [ ] add units in docs - meghna
- [ ] add example images in docs - meghna
- [x] gif option in animate function not working? - all of us
- [ ] to discuss: can we plot tank/res colors if we look at node data? in progress...
- [x] plot_unique_data in animate_plot with mp4 format gives this error: IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (792, 792) to (800, 800) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).
- [x] what does "label" do in draw_nodes? nothing - delete? - meghna. (note: i didn't end up deleting it. "label" = label that shows up for reservoirs, tanks, etc in the base legend)
- [ ] update tests - at the very end
- [x] sometimes multiple plots are created (e.g., if we run the custom data plot for subset of elements in spyder not jupyter notebook)
- [x] change quality units to None
- [x] continuous/discrete links (quality): problems with base_legend and colorbar - tyler
- [ ] jlynn and meghna: test out element_list for continuous/discrete nodes/links (and can test base node/link arguments here too)
- [x] remove legend argument from continuous links and continuous nodes - meghna
- [x] change legend to discrete_legend for discrete plotting functions - meghna
- [x] jlynn and meghna: upload jupyter notebook files
- [ ] docs: update API docs -  jlynn example. look here: https://github.com/tylertrimble/viswaternet/commit/df4c91a9805588e09dcf05272607640a6ea29270, copy from previous version, greatly modify!
- [ ] docs: update all example applications - meghna
- [ ] docs: add figures with function explanations, meghna send jlynn example
- [ ] use tyler's excel file to test animate_plot - meghna
- [x] continuous animate plot: even if we  set 'color_bar_title'  = something, it doesn't show up on the final animated figure (see example 11)
- [x] plot_unique_data - custom_data - node - unique: if we use a subset of data and specify base_node_size and base_node_color, no base nodes show up. note that for link plots changing base_link_color and base_link_width works great! (see example 17)
- [x] example 13: pump links don't show up
- [x] example 18: disable_interval_deleting = False doesn't work in plot_unique_data
- [x] j'lynn - run example 15
- [ ] upload excel file with time varying data - tyler
- [ ] add all docstrings - j'lynn
- [ ] create plot_continuous_nodes figure for docs - j'lynn
- [ ] modify example to show valve arrows

**Comment by tylertrimble** [comment]
Note: build is failing because tests are outdated
